import {
  AlertCircle,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Briefcase,
  CalendarDays,
  Car,
  Check,
  ChevronDown,
  ClipboardPaste,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  Clock,
  Columns3,
  Copy,
  CreditCard,
  Download,
  Droplets,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Fuel,
  Funnel,
  Globe,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  LogOut,
  Menu,
  Minus,
  Moon,
  Package,
  PartyPopper,
  PawPrint,
  Pencil,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  Repeat,
  Search,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sun,
  Tag,
  Target,
  Trash,
  TrendingDown,
  TrendingUp,
  Upload,
  UserCheck,
  UserX,
  Users,
  Utensils,
  Wallet,
  Wifi,
  X,
  Zap,
} from 'lucide-react';

/** Biblioteca única de ícones (lucide). Espessura padronizada em 1.75. */
const ICONS = {
  'alert-circle': AlertCircle,
  'arrow-down-right': ArrowDownRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-right': ArrowUpRight,
  banknote: Banknote,
  'bar-chart': BarChart3,
  bell: Bell,
  'briefcase-business': BriefcaseBusiness,
  briefcase: Briefcase,
  'calendar-days': CalendarDays,
  car: Car,
  check: Check,
  'clipboard-paste': ClipboardPaste,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  clock: Clock,
  columns: Columns3,
  copy: Copy,
  'credit-card': CreditCard,
  download: Download,
  droplets: Droplets,
  ellipsis: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  flame: Flame,
  fuel: Fuel,
  filter: Funnel,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  home: Home,
  landmark: Landmark,
  layers: Layers,
  'piggy-bank': PiggyBank,
  'pie-chart': PieChart,
  'layout-dashboard': LayoutDashboard,
  'line-chart': LineChart,
  'log-out': LogOut,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  package: Package,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  pencil: Pencil,
  percent: Percent,
  'sliders-horizontal': SlidersHorizontal,
  phone: Phone,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  search: Search,
  settings: Settings,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  sun: Sun,
  tag: Tag,
  target: Target,
  trash: Trash,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  'user-check': UserCheck,
  'user-x': UserX,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  x: X,
  zap: Zap,
};

export function Icon({ name, size = 18, strokeWidth = 1.75, className, ...rest }) {
  const Cmp = ICONS[name] || Tag;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" focusable="false" {...rest} />;
}
